### ISSUE TITLE
reorder the videos?

### ISSUE THREAD

**Issue by Pomax** [mozilla/advocacy.mozilla.org#106]
When I load up https://advocacy.mozilla.org/encrypt/2 I get the videos presented as:

![screenshot 174](https://cloud.githubusercontent.com/assets/177243/13361702/24215964-dc75-11e5-94ef-7054635b6406.png)

it feels like it might be better to reorder those, so that they're presented as "1, 2, more" instead.

**Comment by brettgaylor** [comment]
you aren't the first to notice :)

However, we're following the convention of the most recent video released being the "featured", and listing them in descending order from there.

What messes with this is the "coming soon", but we don't want that to appear BEFORE the latest video, right?

**Comment by Pomax** [comment]
Not unless we're used to Japanese itemization =P

That said, would it make sense to "feature" the most recent video differently? E.g. use the "1, 2, more" ordering ("2, 3, more", "5, 6, more" eventually) but then make the center video stand out by make it a fraction larger, and the left/right rects a fraction smaller?

![screenshot 175](https://cloud.githubusercontent.com/assets/177243/13362509/db791daa-dc79-11e5-9041-c667c54f2c9f.png)

**Comment by brettgaylor** [comment]
I think its a design question, and I’m happy deferring to the expertise of @natalieworth :)

**Comment by Pomax** [comment]
(also note I'm mostly commenting as a user here, rather than as mofo person, I had not actually look at the site before >_>;)

**Comment by alanmoo** [comment]
How many videos are planned in total @brettgaylor?

**Comment by brettgaylor** [comment]
2 more videos.  We also may need to feature things that are not videos.  For example, the interactive piece, or a bit of writing, or a petition.

**Comment by ScottDowne** [comment]
I'm doing a bit of cleaning, by trying to move issues to https://github.com/MozillaFoundation/Advocacy or close them where it makes sense.

I don't think we should make any code changes to the existing piece, but this is something that should be brought up during the design process for the next campaign.

Closing.

**Comment by ScottDowne** [comment]
To be fair it's not worth changing the current code simply because it's too late and the ticket is a bit old.

**Comment by alanmoo** [comment]
There was a plan to reorder the videos once the campaign was over, it should just involve changing an Array.push to Arry.unshift (or vice versa)
