### ISSUE TITLE
Design updates to OWF site, close applications

### ISSUE THREAD

**Issue by kristinashu** [mozilla/advocacy.mozilla.org#114]
Based on https://github.com/MozillaFoundation/plan/issues/765

Close OWF applications at midnight (PT) March 20th. Update the messaging on the website on March 21st to:
-     Thank people for their interest
-     Explain the application window is closed
-     Explain that those who've applied will hear from the Open Web Fellows team directly

We should keep the program information available for candidates as we review applications; I think the only major changes would be in the header + footer:
-     Delete "apply now" button
-     New messaging in the footer

**Comment by kristinashu** [comment]
@Melechuga I've mocked up the updates https://redpen.io/hyd170a39c7b5c0e5e

Very minor, just removed the Apply Now button from the top banner and from the bottom banner just above the footer. Can you please suggest some updated copy for the bottom banner?

**Comment by Melechuga** [comment]
Thanks @kristinashu! Text is below; waiting for sign-off from @brettgaylor. 

"**Application Closed**" Thank you to everyone who applied. We will be contacting candidates directly in the next few weeks, and announcing 2016 fellows in June. If you’re interested in what current fellows are doing, please visit [link to the Fellows page].

**Comment by kristinashu** [comment]
Thanks for the copy, I've updated redpen: https://redpen.io/hyd170a39c7b5c0e5e

![openwebfellows-updates_info_overviev 2x](https://cloud.githubusercontent.com/assets/1068783/13762239/c83fff04-e9fa-11e5-9866-8dac3f731d5f.jpg)

**Comment by kristinashu** [comment]
@brettgaylor do these copy changes work for you? https://redpen.io/hyd170a39c7b5c0e5e
Would be great to get approval so I can give these to dev for implementation.

**Comment by Melechuga** [comment]
Hi @kristinashu. @brettgaylor suggested we can be more specific in the text, and say "...contacting candidates in **mid-April.**" Does that work? Thanks.

**Comment by kristinashu** [comment]
Thanks @Melechuga. Sorry I just realized I missed the "announcing 2016 fellows in June" part. So this would be the copy:

Thank you to everyone who applied. We will be contacting candidates directly in mid-April and announcing 2016 fellows in June. If you’re interested in what current fellows are doing, please visit our fellows page.

**Comment by Melechuga** [comment]
That's great! Thanks @kristinashu
