### ISSUE TITLE
[March 21, 2016] Implement updates to OWF site, close applications

### ISSUE THREAD

**Issue by kristinashu** [mozilla/advocacy.mozilla.org#115]
Based on plan issue MozillaFoundation/plan#765 and design https://github.com/mozilla/advocacy.mozilla.org/issues/114

**Deadline March 21, 2016**

Comp: https://redpen.io/hyd170a39c7b5c0e5e

**To do:**
- top banner: delete Apply Now button on all three fellowship pages
- bottom banner: update copy and button link

**Bottom banner copy for Overview and Info page:**
Title: Application Closed
Copy: Thank you to everyone who applied. We will be contacting candidates directly in mid-April and announcing 2016 fellows in June. If you’re interested in what current fellows are doing, please visit our fellows page.
Button: Fellows (link to https://advocacy.mozilla.org/open-web-fellows/fellows)

**Bottom banner copy for Fellows page:**
Title: Application Closed
Copy: Thank you to everyone who applied. We will be contacting candidates directly in mid-April and announcing 2016 fellows in June.
No button.

**Comment by kristinashu** [comment]
@simonwex design has been approved so we're ready to implement

**Comment by mmmavis** [comment]
Just self-assigned. Gonna aim to have a PR ready today so we can push it live next Monday (March 21st)

**Comment by kristinashu** [comment]
Excellent, thanks @mmmavis!
