### ISSUE TITLE
Search engine description is react tags

### ISSUE THREAD

**Issue by gesa** [mozilla/advocacy.mozilla.org#117]
*OS:* ALL
*Browser:* ALL
*Screenshot:* ![](https://snaps.akibraun.com/ct3c1.png)

**Repro Steps:**
1. Search "mozilla encrypt" in Google
2. Find first <https://advocacy.mozilla.org/encrypt/> result (fourth down for me)

**Expected:** Text describing content of the encrypt series
**Actual:**
> `<div data-reactid=".9t9koqax34" data-react-checksum="-1546226859"><div class="encrypt v2" data-reactid=".9t9koqax34.0"><header class="header" ...`

The link redirects to <https://advocacy.mozilla.org/encrypt/social/3>, which is missing a `<meta name="description" content="" />` tag. <view-source:https://advocacy.mozilla.org/encrypt/social/3>

**Comment by brettgaylor** [comment]
@gesa A new framework they said. It'll make everything better they said :)  Thanks for filing!  See you next week!

**Comment by alanmoo** [comment]
Eeek! I believe this should be resolved by https://github.com/mozilla/advocacy.mozilla.org/pull/118, which just went live, but I'll follow up.

**Comment by alanmoo** [comment]
Hmmm...still doesn't have a `meta` description. @brettgaylor, who would be the person to ask for that?

**Comment by valianttry** [comment]
can't we just use existing text: 

"Your online privacy depends on encryption. Learn more about how encryption works, why it's essential to a strong Web, and why it's worth protecting."

Also hoping this takes a total of 30 seconds to fix since i doubt more than 10 people in the world are googling mozilla's encryption campaign.... esp anyone outside mozilla's staff or former staff.

also hi @gesa !!!! :kiss:

**Comment by brettgaylor** [comment]
Hey @alanmoo - is this for the entire site, or just encryption campaign?  If for entire Mozilla Advocacy site, can we use "Building a Global Movement to Protect the Free and Open Web"

**Comment by alanmoo** [comment]
Just the encryption campaign, @brettgaylor. It's been deployed to production and should fix itself next time search engines index the site.

**Comment by alicoding** [comment]
This is now fixed :) 

![](https://dl.dropboxusercontent.com/spa/n5v3bx9nnjkdpzf/dbdhegpc.png)
