### ISSUE TITLE
link to a smaller version of the image on https://discourse.mozilla-advocacy.org/t/welcome-to-mozilla-advocacy-community/81

### ISSUE THREAD

**Issue by davidascher** [mozilla/advocacy.mozilla.org#12]
The image linked (https://blog.mozilla.org/wp-content/uploads/2014/09/mozilla-advocacy_logo.jpeg?8954f8) is huge, which makes this 'welcome' page load slow on people with low bandwidth connections.

**Comment by ScottDowne** [comment]
New site removed this image.
