### ISSUE TITLE
Advocacy content+design+dev communication process 

### ISSUE THREAD

**Issue by lovegushwa** [mozilla/advocacy.mozilla.org#134]
Dig into communication problems identified in Q1 campaign:
(more details about problems here: https://public.etherpad-mozilla.org/p/dev-adv )

What are the problems / pain points around communicating content and specifications for:
- page content (text on a page)
- page variants 
- user flow
- AB testing (share progress, optimizely) 
- GA
- modals (email signup/pledge form & social share)
- UX states
- localization

What are the shared assets that we need in order to have a common language for items listed above?

Stakeholders 
@natalieworth 
@shaghdoosti 
@valianttry
@brettgaylor 
@HPaulJohnson 
@stephaniemcv
@ScottDowne 
@alicoding 

Consulted (please add anyone else that needs to be part of this conversation)
@alanmoo 
@KevZawacki 
@mmika 
@simonwex 
@adamlofting

**Comment by lovegushwa** [comment]
Creating and User-flow docs is a good step towards clarifying: page variants, what and where to AB test, UX states and localization. 

Produce / Website user-flow (webmaker benchmark):
![screen shot 2016-05-06 at 9 48 01 am](https://cloud.githubusercontent.com/assets/12228435/15079841/b5d67368-136f-11e6-87d7-ced57f166d02.png)

User journey (with test variants)
![d60eaaae-bea3-11e5-9204-d319700c356e](https://cloud.githubusercontent.com/assets/12228435/15080011/bed9de40-1370-11e6-8a35-0cd0fc9b1af2.jpg)
 :

**Comment by lovegushwa** [comment]
Next steps:

- Standardize user journey / user flow process & temples (or tools)
- Standardize language! and share it, and agree on it (ie. what we name pages, call page elements, call interactive elements.) would be great if dev's could advise on this.

**Comment by simonwex** [comment]
I love this. @ScottDowne, could you give some feedback?

**Comment by ScottDowne** [comment]
@lovegushwa Can we use vidyo to go over this?

**Comment by lovegushwa** [comment]
@simonwex 

@ScottDowne and I talked about User Flow & User Journey maps.
User Journey (the 2nd image) will be the most beneficial for us since it map's sources of traffic and page variants. The Journey will help us understand all the pages we need to build and provide a key for page names. 

User flow is probably not necessary, we can replace this document with detailed wire-frames and simple AI (we don't build really large sites with many pages at this point.)
