### ISSUE TITLE
staging build failed when pushing to master

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/advocacy.mozilla.org#138]
@alanmoo Not sure, heroku says this: "The account which we use to deploy advocacy-mozilla-org-staging to Heroku via GitHub sync no longer has access to the app. This could be because the person who configured GitHub sync is no longer a collaborator on advocacy-mozilla-org-staging."

Sounds like I don't have permission?

**Comment by alanmoo** [comment]
The connection from @jbuck's account must have changed.

**Comment by alanmoo** [comment]
I don't have admin access to this repo, so I can't connect it. @cadecairos can you help? https://dashboard.heroku.com/apps/advocacy-mozilla-org-staging/deploy/github connect it to this repo.

**Comment by ScottDowne** [comment]
Fun. @alanmoo I think I had access and it seems it worked.

**Comment by ScottDowne** [comment]
Fixed now and staging is built. I had to do a manual build just on my one patch, but from here out should be fine.
