### ISSUE TITLE
Design for OWF refresh

### ISSUE THREAD

**Issue by hannahkane** [mozilla/advocacy.mozilla.org#155]
See https://github.com/MozillaFoundation/plan/issues/812 for details

**Comment by Melechuga** [comment]
tagging me; need to tag Vanessa when she gets access.

**Comment by kristinashu** [comment]
Tag! I'll most likely be doing the design for this.

**Comment by Melechuga** [comment]
cc @vanessarhinesmith

**Comment by vanessarhinesmith** [comment]
Tag < > I'm in.

**Comment by hannahkane** [comment]
Going to move this to the current heartbeat to get started, but pending conversation with @kristinashu about her time.

**Comment by kristinashu** [comment]
Content ticket is here https://github.com/mozilla/advocacy.mozilla.org/issues/168 and I'll do design once we have the updated content.

**Comment by kristinashu** [comment]
Here's the Overview page https://redpen.io/ohdc7928c54c717e74 but I'm still working on the Fellows page.

@Melechuga @vanessarhinesmith let me know if this is what you had in mind.

**Comment by Melechuga** [comment]
Thanks! I added some thoughts in the redpen. I think we're really looking to follow the esthetic (but not the color scheme) of the Science fellowship website too.

**Comment by kristinashu** [comment]
Ok cool, I've updated the Overview page to look more like the science site https://redpen.io/ohdc7928c54c717e74

**Comment by kristinashu** [comment]
Also just added the fellows page https://redpen.io/p/uqc9cc59bb9eec5986

**Comment by kristinashu** [comment]
@sabrinang for design review please

**Comment by kristinashu** [comment]
Made a few minor copy updates and added a placeholder FAQ page https://redpen.io/p/uqc9cc59bb9eec5986

cc @gvn @alanmoo looks like OWF will have a very similar layout to the Science Fellows pages.

**Comment by kristinashu** [comment]
I've updated the comps with the 2016 bio pics (both a purple overlay version and a full color version), 2016 bio copy, and FAQ copy: https://redpen.io/p/uqc9cc59bb9eec5986

We're still missing a few bios but should get them soon. Also just need a little intro copy for above the bios.

**Comment by vanessarhinesmith** [comment]
@kristinashu this looks A-mazing! I  really like the full color version of the photos ... what do others think? I will have the last three bios completed (hopefully) tomorrow and will write up an intro copy as well.

**Comment by kristinashu** [comment]
Excellent, thank you @vanessarhinesmith

**Comment by vanessarhinesmith** [comment]
We have the last remaining bios and pictures. W00T! I have updated the Google document: https://docs.google.com/document/d/1pRdmICQTJSrY3eE2wcIa1BcSIeRdqmq-RFFn0XSOb3s/edit and added the images to the Google Drive folder: https://drive.google.com/drive/u/1/folders/0B32kLgMrp9LuV19aQU1mUEpWUVE Many thanks, all, and go team!

**Comment by kristinashu** [comment]
Here's the updated the comp with the latest bio pics and copy: https://redpen.io/p/uqc9cc59bb9eec5986

I've also added a link to the organization's website below each fellow's name.

I think we're all set for implementation in https://github.com/mozilla/advocacy.mozilla.org/issues/156

**Comment by Melechuga** [comment]
Thanks @kristinashu! So sorry for the late notice, but just realized I hadn't adequately updated the 2015 fellows' (alumni) bios. I've rewritten them [here](https://docs.google.com/a/mozilla.com/document/d/1NIBNibBH-sjImRyk5sF8zBQxcasHwJw_VnVG3rDTm4w/edit?usp=sharing). Thank you!

**Comment by kristinashu** [comment]
No worries, I've update the comps and copy doc: https://redpen.io/p/uqc9cc59bb9eec5986 and https://docs.google.com/document/d/1pRdmICQTJSrY3eE2wcIa1BcSIeRdqmq-RFFn0XSOb3s/edit
