### ISSUE TITLE
(On August 1, not before) Implement OWF refresh

### ISSUE THREAD

**Issue by hannahkane** [mozilla/advocacy.mozilla.org#156]
See #155 

<s>Deadline is July 1st at the latest, but ideally before.</s.>

Go Live date is August 1

**Comment by Melechuga** [comment]
tagging me; need to tag Vanessa when she gets access.

**Comment by kristinashu** [comment]
Comps are very similar to Science Fellowships section https://science.mozilla.org/programs/fellowships 

Redpen comps: https://redpen.io/p/uqc9cc59bb9eec5986

Illustrator file: https://drive.google.com/open?id=0B2irLVDJivhLU3FwMFBpQnZieTA

Copy (links to FAQ and Fellow bios in the doc): https://docs.google.com/a/mozilla.com/document/d/1-Usw1YWS_GgbcC6rOC9el3wl8JIeJSDfNeHZDv8FeSc/edit?usp=sharing
copy for 2015 bios are here (please remove quotes): https://advocacy.mozilla.org/en-US/open-web-fellows/

2016 bio pic JPGs: https://drive.google.com/open?id=0B2irLVDJivhLTTBrSmtTZFB5QzA

Icon assets can be pulled from Science site: https://science.mozilla.org/programs/fellowships

**Comment by hannahkane** [comment]
cc @alanmoo and @gvn to discuss the best path forward, given the tight deadline

cc @simonwex

**Comment by kristinashu** [comment]
There were some copy updates so I've just updated the above links (copy doc, illustrator, redpen) ^

**Comment by alanmoo** [comment]
This has been pushed to production- there might be a little bit of a delay though, as the site is behind a CDN.

**Comment by vanessarhinesmith** [comment]
W00T! Thank you all. You rock!!
