### ISSUE TITLE
Design assets for OWF one-year report

### ISSUE THREAD

**Issue by hannahkane** [mozilla/advocacy.mozilla.org#165]
The draft document is here: https://docs.google.com/document/d/15ozoyElpjgfhCRA9t1PgqRx-KrDtL4k2yDfn9t8Rm5s/edit

We'll use the [Web Literacy Whitepaper](http://mozilla.github.io/content/web-lit-whitepaper/) as a template for the design, though we'll add design elements as needed.

### Design TODOs
 - [x] Choose a color for the template
 - [x] Identify or design a graphical element for the top left corner
 - [x] create a pullquote style (note: should be added to Onesie)
 - [x] photo treatments (photos to be provided by OWF team)
 - [x] bar graphs (details and data to be provided by OWF team)
 - [x] a map with data about where applications were sourced (data to be provided by OWF team)
 - [x] ensure the print stylesheet works and looks good

**Comment by hannahkane** [comment]
Suggesting we start on this *next* heartbeat, but @KevZawacki @Melechuga and @vanessarhinesmith might want to add items to the list above in the meantime. 

@kristinashu, if you have time you might want to review the draft content and see if you can identify additional design tasks as well.

**Comment by kristinashu** [comment]
Sounds good! 

@flukeout @vazquez can you please share any design files you have for the Web Literacy Whitepaper and any other similar templates? I also vaguely remember a quote treatment, have either of you done one before?

**Comment by kristinashu** [comment]
Few other templates for reference:
http://flukeout.github.io/curriculum-testing/intermediate-web-lit-two-updates/session01-buttons-and-alerts.html#overview
http://mozilla.github.io/learning-networks/clubs/afterschool-program/
http://mozillascience.github.io/working-open-workshop/

**Comment by kristinashu** [comment]
Here's the initial comp: https://redpen.io/kxaf01224594be1426

I'm suggesting we use purple as the template color and the logo in the top corner. Also added a simple pull quote treatment, since there are quite a few quotes.

I still need to add photos, graphs, and maps.

**Comment by KevZawacki** [comment]
@kristinashu This looks great! 😄 Really like the pull quote style.

+ @Melechuga for additional feedback.

**Comment by vanessarhinesmith** [comment]
We'll want to think about where we should link the report from on the revised website. 

We have time on this - but good food for thought as we're working on both in parallel.

**Comment by hannahkane** [comment]
Nice work, @kristinashu. Adding a note here about what we discussed earlier—I think we should explore some paginated options to help with readability. Adding images will help with that, too.

**Comment by kristinashu** [comment]
I've mocked up all the pages of the report: https://redpen.io/p/qa0d7b5c69cd064069

@KevZawacki @vanessarhinesmith @Melechuga let me know your thoughts. In the interest of time I didn't style every quote and link but there should be enough there to give you an idea of what it would look like.

**Comment by KevZawacki** [comment]
@kristinashu This looks **awesome** Thank you!

I should have read your above comment more closely -- you can ignore my "pull quote" and "hyperlink" comments in the RedPen. Oops. 😭 

cc @brettgaylor in case he'd like to take a peek.

Is it looking like the publication will be ready & published by July 18? That would be excellent -- we have a Fellows event slated for then.

**Comment by kristinashu** [comment]
@KevZawacki thanks! 

@hannahkane does July 18 sound good to you? From what I understand, @flukeout will need to do some prep work #203 and then it will be on @KevZawacki to add the content #204. This way, Kevin will have full control over the content and be able to edit text, add links, quotes and add/remove images!

**Comment by hannahkane** [comment]
Yes, I think July 18th is reasonable. Thanks to both of you!

**Comment by flukeout** [comment]
Sounds good, I'll review the designs and chime in if I have any questions. Where will this live when it's published?

**Comment by hannahkane** [comment]
Good question. What do you think about putting it here: https://github.com/mozilla/content?

**Comment by KevZawacki** [comment]
ping @Melechuga & @vanessarhinesmith, who might have ideas on where it lives

**Comment by KevZawacki** [comment]
c @Melechuga & @vanessarhinesmith, who might have ideas on where it lives

**Comment by vanessarhinesmith** [comment]
Great question. I honestly don't have a good response. Hannah's suggestion works for me. But let's see if Melissa has any preference or suggestions.

**Comment by Melechuga** [comment]
Hi @hannahkane, I think your suggestion is great; we'd just want to link to it from both the adv.m.o page (one of the "tiles") and from the OWF page. Thanks!
