### ISSUE TITLE
Content for OWF refresh 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/advocacy.mozilla.org#168]
See MozillaFoundation/plan#812 for details

We will need copy:
- [x] To welcome and announce the 8 new fellows
- [x] Revised and shortened info page copy
- [x] Short bios of each fellow, the work they'll be doing at their host orgs (Include twitter handles of each fellow, links to host org websites)
- [x] Possible changes needed to the fellows site to make it an alumni page

Images:
- [x] photos of the new fellows

**Comment by Melechuga** [comment]
@vanessarhinesmith and I are hacking [on this doc](https://docs.google.com/document/d/1-Usw1YWS_GgbcC6rOC9el3wl8JIeJSDfNeHZDv8FeSc/edit) to get the copy in place. Will ping @KevZawacki when it's ready. Our plan is to have a workable draft by next Wednesday (June 1).

**Comment by kristinashu** [comment]
Perfect, thanks!

**Comment by kristinashu** [comment]
@Melechuga @vanessarhinesmith just checking in to see if this is still on track, do you still think it will be ready tomorrow?

**Comment by vanessarhinesmith** [comment]
Yes. We are still on track. 
We're hacking the document tomorrow afternoon (PST/EST).
We should be good with time. 
Thanks for checking in. Appreciated!

**Comment by Melechuga** [comment]
@KevZawacki Can you take a look at our copy draft for the website? (Also linked it in the OWF comms calendar): https://docs.google.com/document/d/1-Usw1YWS_GgbcC6rOC9el3wl8JIeJSDfNeHZDv8FeSc/edit

@kristinashu As soon as @KevZawacki gives his a-ok, we're good to go!

**Comment by kristinashu** [comment]
Thanks @Melechuga! This is enough to get me started so no rush on this @KevZawacki 

Do you also have bios and pics for the new fellows?

**Comment by Melechuga** [comment]
@kristinashu Not yet; will let you know when we do. For the bios + pics, we're going to follow the same model as [last year](https://advocacy.mozilla.org/en-US/open-web-fellows/fellows) (~100 words), and want to follow the same design as Science. Does that work?

**Comment by kristinashu** [comment]
Sounds good!

**Comment by kristinashu** [comment]
Here's the Overview page comp if you want to see the copy in context https://redpen.io/ohdc7928c54c717e74

**Comment by KevZawacki** [comment]
@Melechuga Just added minor edits to [this copy](https://docs.google.com/document/d/1-Usw1YWS_GgbcC6rOC9el3wl8JIeJSDfNeHZDv8FeSc/edit). If there's anything else in need of an edit, let me know. 

Do we have a rough idea of when we'll publicly announce the 2016/17 fellows?

**Comment by vanessarhinesmith** [comment]
@kristinashu I just uploaded the last three bio pictures [here](https://drive.google.com/drive/u/1/folders/0B32kLgMrp9LuV19aQU1mUEpWUVE)
@KevZawacki I just assed the last three bio summaries [here](https://docs.google.com/document/d/1pRdmICQTJSrY3eE2wcIa1BcSIeRdqmq-RFFn0XSOb3s/edit)

**Comment by kristinashu** [comment]
Thank you all for the content! I'm finishing up the design work in https://github.com/mozilla/advocacy.mozilla.org/issues/155
