### ISSUE TITLE
Private eye activity will be deprecated

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/advocacy.mozilla.org#20]
The activity featured on the advocacy landing page will be archived soon. You could:  
 - add a redirect from https://webmaker.org/en-US/private-eye to https://old.webmaker.org/en-US/private-eye.
 - or move the activity to the MLN site. 

See related: https://github.com/mozilla/webmaker.org/issues/1423

**Comment by ScottDowne** [comment]
New site removed this, closing.
