### ISSUE TITLE
Link to OWF report from advocacy.mozilla.org

### ISSUE THREAD

**Issue by kristinashu** [mozilla/advocacy.mozilla.org#202]
Based on @vanessarhinesmith comment in [design OWF Report](https://github.com/mozilla/advocacy.mozilla.org/issues/165) - we'll want to think about where we should link the report from on the [revised website](https://github.com/mozilla/advocacy.mozilla.org/issues/156).

**Comment by vanessarhinesmith** [comment]
@KevZawacki Thoughts on where we should like the report from the updated Open Web Fellows site. Here is the site mock-up: https://redpen.io/ohdc7928c54c717e74

**Comment by KevZawacki** [comment]
@vanessarhinesmith How about a sentence after the paragraph "Fellows are makers and doers..." but before the header "Expectations of Fellows"?

If could be: "Read the report-out on Year 1 of the Fellowship" w/ hyperlink.

**Comment by vanessarhinesmith** [comment]
That totally works. What is the ETA on the report? With the site launching August 1st we might be able to have the report linked right from the get go.

**Comment by kristinashu** [comment]
@Melechuga mentioned in https://github.com/mozilla/advocacy.mozilla.org/issues/165 we should also link to the report in one of the adv.m.o home page "tiles" as well. 

I think it could replace the current Open Web Fellows tile. Any copy suggestions?

**Comment by KevZawacki** [comment]
@Melechuga @kristinashu 

We can likely keep the hed and copy the same, and change the button to "Read our Year 1 Report." Thoughts?

**Comment by Melechuga** [comment]
@kristinashu @KevZawacki adding @vanessarhinesmith 
Yea, I think we can change the button per Kevin's suggestion. When we announce the fellows, though, it'd be good for those to be separate tiles, so people can see both. Does that work? 

On a separate note, we'd want to incorporate a link to the Year 1 report on the adv.m.o-OWF page. Thanks!

**Comment by kristinashu** [comment]
Opened a new ticket to implement these updates https://github.com/mozilla/advocacy.mozilla.org/issues/216
