### ISSUE TITLE
Dev updates to OWF one-year report template

### ISSUE THREAD

**Issue by kristinashu** [mozilla/advocacy.mozilla.org#203]
Based on design https://github.com/mozilla/advocacy.mozilla.org/issues/165 and [Redpen comps](https://redpen.io/p/qa0d7b5c69cd064069)

We will need to make some updates to the paginated version of the [template] (http://flukeout.github.io/curriculum-testing/intermediate-web-lit-two-updates/session01-buttons-and-alerts.html#overview)

Updates needed:
- [x] review design to make sure everything is possible using markup 
- [x] fix nav bug: clicking on the side nav should bring a user to the top of the page content, right now if shows partway down the page
- [x] double check that it will print nicely
- [x] add quote style

cc @flukeout @hannahkane

**Comment by kristinashu** [comment]
@flukeout I think you've done all of these ^

**Comment by flukeout** [comment]
Correct! It's all ready and awaiting the final updates in the content repo. I'll be meeting with Kevin tomorrow to give him a walkthrough.

https://github.com/mozilla/content
