### ISSUE TITLE
Build and add content to OWF one-year report 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/advocacy.mozilla.org#204]
Based on design https://github.com/mozilla/advocacy.mozilla.org/issues/165
- Redpen comps [here](https://redpen.io/p/qa0d7b5c69cd064069)
- Copy doc [here](https://docs.google.com/document/d/15ozoyElpjgfhCRA9t1PgqRx-KrDtL4k2yDfn9t8Rm5s/edit)
- Image assets [here](https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLbC1DQ1JCd0tUMU0&usp=sharing)

Template should be the paginated version (similar to http://flukeout.github.io/curriculum-testing/intermediate-web-lit-two-updates/session01-buttons-and-alerts.html#overview). 

I believe the plan is:
- [x] @flukeout to make template updates listed in https://github.com/mozilla/advocacy.mozilla.org/issues/203
- [x] @flukeout will give @KevZawacki @hannahkane @kristinashu a tutorial on how to set up the GitHub page
- [x] @KevZawacki will add the content
- [ ] design review once content has been added

Deadline is July 18

@hannahkane does that sound right?

**Comment by hannahkane** [comment]
Yes, that's the plan!

**Comment by flukeout** [comment]
@kristinashu Can you please add the mozilla Advocacy logo to the asset folder as well? SVG format would be ideal, cheers.

**Comment by flukeout** [comment]
The template is ready to go in the [content repo](https://github.com/mozilla/content).

**Comment by kristinashu** [comment]
ACLU logo is wack in FF 47
<img width="386" alt="screen shot 2016-07-06 at 2 09 11 pm" src="https://cloud.githubusercontent.com/assets/1068783/16634579/3fbddeac-4383-11e6-99b9-1314ff0ca69d.png">

**Comment by flukeout** [comment]
Changed some styling that should address the issue above.

**Comment by KevZawacki** [comment]
Hey @kristinashu and @flukeout 

I've just finished populating, and copy/pasted the new code into GitHub. You can see the result [here](http://mozilla.github.io/content/open-web-fellows-report/#introduction).

It was a pretty painless process -- thanks for the guidance!

OK to share with Vanessa and Melissa so they can QA, as well?

**Comment by kristinashu** [comment]
@KevZawacki nice, looks good to me! 

I just realized the graphs are missing so we've added those to the Looking Ahead section, you might want to change the titles tho (Melisa added a comment in redpen https://redpen.io/re4316e83105945b7a).

cc @vanessarhinesmith @Melechuga please feel free to look over the report [here](http://mozilla.github.io/content/open-web-fellows-report/#introduction).

**Comment by flukeout** [comment]
Going to close as the report is now live. Further issues can be filed on the [content repo](github.com/mozilla/content) where the report is hosted.
