### ISSUE TITLE
Localization strategy for videos

### ISSUE THREAD

**Issue by brettgaylor** [mozilla/advocacy.mozilla.org#209]
Now that we are live on Pontoon, we're starting to see lots of locales translate the site and ask for it to be on production.

When we have videos on our site, it presents a bit of a problem: not all of our videos are localized either with audio (dubbing - as we did in spanish and german for encryption2), or with subtitles.

It would be great if we could somehow indicate to localizers that they can localize the video on Amara (when applicable), and that this would be a requirement for a locale being considered localized.  This would also require us hosting videos in a way that is compliant with Amara (eg youtube).

**Comment by ScottDowne** [comment]
Migrated to https://github.com/MozillaFoundation/Advocacy/issues/212

Closing.
