### ISSUE TITLE
Duplicate content in a l10n string

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/advocacy.mozilla.org#224]
https://github.com/mozilla/advocacy.mozilla.org/blob/984f4b4f307f142b46e7555cca880547349cc0fc/locales/en-US/encrypt.properties#L27-L28

This is most likely just an oversight.

**Comment by ScottDowne** [comment]
Fixed in https://github.com/mozilla/advocacy.mozilla.org/commit/c247b21c70091bc0943f61688ff77c579dfc6b13

**Comment by mathjazz** [comment]
@ScottDowne Thanks for the quick fix.

Please note that our tools treat moved strings as untranslated. To avoid that, you need to move them in locale files, too.

**Comment by ScottDowne** [comment]
@mathjazz Not sure I fully understand. Just to clarify:

I should move them in all localized string files, not just en-US?

Also, is there anything actionable you're asking me to do? Or is this for next time, and you handled it this time?

**Comment by mathjazz** [comment]
> I should move them in all localized string files, not just en-US?

Yes.

> Also, is there anything actionable you're asking me to do? Or is this for next time, and you handled it this time?

If you could move strings removed by @mozilla-pontoon after you landed this patch to the right place, localizers would appreciate it, otherwise they have to retranslate the strings. Please note that German (de) is already done and doesn't need any further action.

**Comment by ScottDowne** [comment]
Done, it's on staging.

Let me know if I missed something.

I noticed de and hu beat me to it.

**Comment by mathjazz** [comment]
Thanks for taking care of this, @ScottDowne!

A quick question - where are the strings in the new file `fellows.properties` located on the actual site? I can bind them to one or more of the 14 subpages we have listed for in-context localization, or I can simply display it as a separate resource (like homepage or snippet):
https://pontoon.mozilla.org/sl/mozilla-advocacy/

Subpage URLs:
https://advocacy-mozilla-org-staging.herokuapp.com/en-US/encrypt/social/{1-4}
https://advocacy-mozilla-org-staging.herokuapp.com/en-US/encrypt/hybrid/{1-4}
https://advocacy-mozilla-org-staging.herokuapp.com/en-US/encrypt/direct/{1-4}
https://advocacy-mozilla-org-staging.herokuapp.com/en-US/encrypt/signup
https://advocacy-mozilla-org-staging.herokuapp.com/en-US/encrypt/signup-complete

**Comment by ScottDowne** [comment]
Right now, the fellows stuff is just starting to take a localized focus, but so far if we add new text, we add it in a l10n savvy way, but old text still needs and update.

The pages for fellows are:

https://advocacy.mozilla.org/en-US/open-web-fellows/fellows2016
https://advocacy.mozilla.org/en-US/open-web-fellows/fellows2015
https://advocacy.mozilla.org/en-US/open-web-fellows/overview
https://advocacy.mozilla.org/en-US/open-web-fellows/info

And the pages for home are:

https://advocacy.mozilla.org/en-US/

**Comment by mathjazz** [comment]
OK, once more string are added to the fellows.properties files, feel free to ping me and I'll add these pages (with staging URLs) and bind them to the file. For now I'll just keep the file without in-context localization.
