### ISSUE TITLE
Content updates to Open Web Fellows 

### ISSUE THREAD

**Issue by vanessarhinesmith** [mozilla/advocacy.mozilla.org#265]
(attn: @alanmoo)

Launching 2017 call for new host organizations so a few small content updates to: 

https://advocacy.mozilla.org/en-US/open-web-fellows/fellows2016

All updates are highlighted in yellow in this Google document: 

https://docs.google.com/a/mozilla.com/document/d/1d3tsbFEAIxOWKtXc16gleEuv8qhzzqSBVgdlfo5x54U/edit?usp=sharing

Thank you!! 👯

**Comment by alanmoo** [comment]
Should this go live as soon as it's ready?

**Comment by vanessarhinesmith** [comment]
Yes please 👍
