### ISSUE TITLE
[Mobile] advocacy.mozilla.org is janky

### ISSUE THREAD

**Issue by Melechuga** [mozilla/advocacy.mozilla.org#27]
When viewing advocacy.mozilla.org on mobile the text + buttons are misaligned.

**Comment by ScottDowne** [comment]
I'm not seeing it, can you add a bit more info or maybe a screenshot? Maybe I need to test on a different device, or I'm not looking in the right spot or right context?

**Comment by ScottDowne** [comment]
oh, lol, this was the old site wasn't it?

Sept 10 2015. Closing.
