### ISSUE TITLE
Net Neutrality input form is too short in Safari

### ISSUE THREAD

**Issue by alanmoo** [mozilla/advocacy.mozilla.org#296]
<img width="487" alt="screenshot 2017-05-08 18 14 57" src="https://cloud.githubusercontent.com/assets/1682681/25827647/436730d4-341a-11e7-91bb-a24cc116e1b6.png">

Swapping `height: 45px` with `margin-top: 0` seems to fix it.

**Comment by ScottDowne** [comment]
Thanks for catching this. Me and Becca had a pretty quick change to reduce the overall height of the form, so we reduced the input height, and didn't notice this.

Change in #297 seems to do the job.
