### ISSUE TITLE
Remove auto moz://a encoding on 2FA page

### ISSUE THREAD

**Issue by brettgaylor** [mozilla/advocacy.mozilla.org#356]
We don't want "mozilla" to be rendered as "moz://a" on the 2FA page as shown below
![image](https://user-images.githubusercontent.com/345974/27300050-3e3ad662-54e3-11e7-8c12-f051f02e9f40.png)

can you release the hackfix?

**Comment by ScottDowne** [comment]
Just doing some cleanup of assigned issues and looks like this one got fixed.

https://advocacy.mozilla.org/en-US/safety/2fa

Closing.
