### ISSUE TITLE
askjoin@mozilla.org and joinmozilla@mozilla.org Storage Full notices

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/advocacy.mozilla.org#373]
I'm getting a bunch of these for askjoin@mozilla.org and joinmozilla@mozilla.org in Desk.com. The email headers aren't flagging as spam...but it doesn't look right. 

Can you investigate? I know these are older mail lists and not groups, so on the off chance it's legit, I don't have access. I assigned a bunch of them to you in Desk.com.

**Comment by cadecairos** [comment]
@stephaniemcv is this still a problem?

**Comment by stephaniemcv** [comment]
I'm still seeing notices, but at this point I think most of them are phishing attempts. Maybe it's a simple task for the new person to look into? ;-)

![image](https://user-images.githubusercontent.com/11812272/30993854-19dcc994-a46e-11e7-9e71-c384d07a9e8a.png)

**Comment by cadecairos** [comment]
Going to close this out, lets re-open if it's still a problem.
