### ISSUE TITLE
Update on Open Web Fellows 2017 pages

### ISSUE THREAD

**Issue by auremoser** [mozilla/advocacy.mozilla.org#381]
Hello Advocacy website team!

### Context
We'll be announcing our fellows for 2017 this week. I'm happy to update the advocacy site accordingly but am not sure about the appropriate procedure, is it the same Gitflow workflow as the [Science Site](https://github.com/mozilla/science.mozilla.org/#git-flow) or is there a better PR workflow I should follow?

### Content to update
Here are the updates, let me know if I should handle this or if someone can help! :

* [x] add a page for the 2017 fellows bios (like the [2016 fellows](https://advocacy.mozilla.org/en-US/open-web-fellows/fellows2016))
* [x] add the content for the fellows bios in the same format as the 2016/2015 fellows
* [x] update the [blog](https://blog.mozilla.org/netpolicy/) with an announcement about the fellows, not sure if this should be done on Medium (as Vanessa did in the past) or on the netpolicy blog attached to this site, recommendations welcome.

### Suggestions
I attached a doc with the bio info as a markdown doc (2017-owf-bios.txt - apparently ghub only supports txt attachements, not md)  in case that's easy to update directly, along with the images for each fellow. I can also update it myself if you'd like to tell me the best practice for that.

[2017-owf-bios.txt](https://github.com/mozilla/advocacy.mozilla.org/files/1278080/2017-owf-bios.txt)
[owf-imgs.zip](https://github.com/mozilla/advocacy.mozilla.org/files/1278085/owf-imgs.zip)

If you want to slack me the creds or contacts for the blog (or otherwise indicate that I should post elsewhere, say, on medium) that would be grand!

Thank you so much!

cc/ 
@brettgaylor  - in case he'd like me to add the Media Art fellows bios/contacts to the Advocacy site? 
@community-impact

**Comment by brettgaylor** [comment]
Yeah I think it would be nice to add media fellows, since there won't be any other page to host/announce.

Though wondering if we shouldn't have this page on network site? (ducks boo thrown at him)

Whatever we do I think it should be a page that sticks around for that cohort - folks will want to be able to link to it down the line.

**Comment by auremoser** [comment]
Yep totally @brettgaylor , I've added an issue for that [here](https://github.com/mozilla/network/issues/715). 

For now we should probably update all pages, as some folks will find them and wonder why they're not updated.

**Comment by brettgaylor** [comment]
🤔😀👏

**Comment by alanmoo** [comment]
Looks like if you open a PR against master on this repo it'll be the right approach.

**Comment by auremoser** [comment]
Closing this issue as it's up!
