### ISSUE TITLE
Apply Now section, PST or PDT?

### ISSUE THREAD

**Issue by t1msammut** [mozilla/advocacy.mozilla.org#43]
The "Apply Now" section on many of the pages shows the application deadline as 11:59pm PST March 20, 2016. However, daylight savings time starts on March 13 this year. Should that be PDT instead of PST?

![screenshot from 2016-02-02 13-58-16](https://cloud.githubusercontent.com/assets/10746039/12751420/00cd61ba-c9b5-11e5-8b3c-0d17af47eb3a.png)

**Comment by Melechuga** [comment]
@t1msammut Great catch! Yes, it should be PDT. 

@ScottDowne Can you please change this on all instances where it says the deadline is 11:59 PST? Thank you!

**Comment by ScottDowne** [comment]
Updated
