### ISSUE TITLE
update link to the host org blog post

### ISSUE THREAD

**Issue by kristinashu** [mozilla/advocacy.mozilla.org#46]
Host org blog post is now up https://blog.mozilla.org/netpolicy/2016/02/01/2016-open-web-fellows-program-host-organizations/ 

@ScottDowne can you please update the link under Host Organizations on http://advocacy.mozilla.org/open-web-fellows/ ?

cc @Melechuga

**Comment by ScottDowne** [comment]
Was done this morning.

**Comment by ScottDowne** [comment]
Hm, maybe I got this wrong.

**Comment by ScottDowne** [comment]
I had the wrong link changed, I noticed when I read this description that it was wrong. It's fixed properly now.
