### ISSUE TITLE
add encryption banner to home page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/advocacy.mozilla.org#48]
Design and implement banner for encryption campaign. 

Banner will need to go live at the same time as the encryption campaign - Feb 10th.

cc @ScottDowne @cassiemc

**Comment by kristinashu** [comment]
For my reference, campaign design is here https://github.com/MozillaFoundation/encryption_campaign/issues/40#issue

**Comment by ScottDowne** [comment]
I'll be on PTO Feb 8th, but I can have it ready to go Friday, just someone else needs to hit "go"

**Comment by kristinashu** [comment]
Ok, sounds good. I should have the design done today.

**Comment by kristinashu** [comment]
@lovegushwa here's how the campaign banner looks on advocacy https://redpen.io/p/wt1d64bfb93fa6a6b8 - does that work for you?

**Comment by lovegushwa** [comment]
@kristinashu yes it works! (colors look muted but I think that's a github / redpen thing.)

**Comment by kristinashu** [comment]
Thanks @lovegushwa, yeah colours should be the same.

@ScottDowne here's the comp: https://redpen.io/p/wt1d64bfb93fa6a6b8

ENCRYPT text (SVG and PNG options): https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLeWE1cjZELU9PT28&usp=sharing

Background colour:  #073E76

Banner height is 800px (a little taller than the other secondary pages).

**Comment by kristinashu** [comment]
@ScottDowne will you be able to set this up before you go?

**Comment by ScottDowne** [comment]
I can try to do it before I leave today.

**Comment by HPaulJohnson** [comment]
Heads up: the campaign launch date is actually 2/10 so promo should go live then (not 2/8 as stated above). cc/ @lovegushwa

**Comment by kristinashu** [comment]
Thanks @HPaulJohnson, I've updated the comment above. Do you know what the URL will be?

**Comment by kristinashu** [comment]
We think the URL will be a.m.o/encrypt but will need to confirm.

**Comment by HPaulJohnson** [comment]
confirmed - URL will be advocacy.mozilla.org/encrypt

**Comment by ScottDowne** [comment]
I created a pull request for this here: https://github.com/mozilla/advocacy.mozilla.org/pull/54

It should be tested before Tuesday and ready to ship for Wednesday (10th)

I have a live demo for this here: http://tranquil-hollows-89070.herokuapp.com/

@alicoding @alanmoo @jbuck One of you probably wants to do a test on this too.

**Comment by jbuck** [comment]
@HPaulJohnson is there a specific ship time tomorrow?

**Comment by kristinashu** [comment]
@jbuck looking at https://github.com/mozilla/teach.mozilla.org/issues/1619#issuecomment-182098921 it sounds like the encryption micro site won't be launching tomorrow, so we won't be pushing this update tomorrow.

**Comment by HPaulJohnson** [comment]
just to clarify: the microsite will be launching tomorrow but we are not doing any active promotion out of the gate and therefore don't want the teach. banner to go live.

**Comment by HPaulJohnson** [comment]
Update: we can go live with this on Tuesday 2/16 as part of the kickoff of official promotion of this campaign.

**Comment by alicoding** [comment]
This is now done and live here https://advocacy.mozilla.org/

**Comment by kristinashu** [comment]
Looks great, thanks @alicoding!
