### ISSUE TITLE
design and implement email sign up on home page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/advocacy.mozilla.org#49]
Based on https://github.com/MozillaFoundation/movement-building/issues/82

Lets make the home page email sign up the same functionality and similar look as on the encryption campaign micro site - https://github.com/MozillaFoundation/encryption_campaign/issues/40#issue

I think this will be a sign up button which opens a form asking for user's name, email and country.

@ScottDowne I'll updated the design today and then hopefully you can work with whoever is building the mirco site and reuse some of the code. 

cc @cassiemc

**Comment by ScottDowne** [comment]
@kristinashu just to confirm, that means we want country dropdown now? Given that the micro site has country too.

**Comment by kristinashu** [comment]
@ScottDowne yeah I think it will need to have name, email and country drop down to be consistent. Although I would love to AB test sign up forms - one with the three fields and one with just email sign to see if more having fields is a deterrent. 

@HPaulJohnson do you think this is worth testing or do we have to have the three fields? I'm curious what the reasoning is behind asking for the name and country?

**Comment by kristinashu** [comment]
@cassiemc could I please get your thoughts on these two email sign up options?
Home - 1 field email sign up: https://redpen.io/p/wt1d64bfb93fa6a6b8
Home - 3 field email sign up: https://redpen.io/p/wt1d64bfb93fa6a6b8

Also opened a ticket about check boxes https://github.com/mozilla/teach.mozilla.org/issues/1632

**Comment by cassiemc** [comment]
@kristinashu I woudn't worry about testing for now, something we can optimize later. Mostly just need to get the ability to sign up form on there :) Not sure what the redpens are... maybe add screenshots here?

**Comment by cassiemc** [comment]
As said on mattermoz, let's do whatever was done on the encryption site to save dev time. We can test that later, maybe can file as a followup bug. It'd be a good thing to know! And it's likely that adam or andrea may already have data on it too

**Comment by kristinashu** [comment]
I've made a new redpen with the three options: https://redpen.io/p/cp9085ec873c887b3c
I think all three would have similar dev time. @alanmoo you would most likely be building this email sign up so please feel free to weight in if you have any preferences or concerns.
I think option 1 offers the best usability.

**Comment by kristinashu** [comment]
Closing this since no one is really asking for it to be done, not sure it is necessary.
