### ISSUE TITLE
Add Smart TV content to *PNI

### ISSUE THREAD

**Issue by alanmoo** [mozilla/advocacy.mozilla.org#496]
Smart TV image: https://drive.google.com/drive/u/1/folders/1zfwGqBfS6n3y-z6UTQSvSuQ3f5GWycNU

**Comment by alanmoo** [comment]
@caltrider Is this content you're providing?

**Comment by caltrider** [comment]
@alanmoo Yes. Janice was working to have reviews finalized by tomorrow. Hopefully we'll have that content for the guide soon and it will be easy to add.

**Comment by alanmoo** [comment]
Great. Please comment back here when you've got them and reassign the issue to @gvn.

**Comment by natalieworth** [comment]
We're still waiting on the content to be finalized for the Streaming Section, but here are the photos for the products: https://drive.google.com/drive/u/1/folders/1ln2Trsfsx_Z17l6dQx_M0CKf7IS-ICdr
cc @gvn @alanmoo @caltrider @beccaklam

**Comment by natalieworth** [comment]
Also just noting from @caltrider that the title of the category should be “Streaming TV” rather than smart TV (we’re not actually reviewing any tvs, just the devices that let you stream things to them.

**Comment by alanmoo** [comment]
Is this still going to be happening?

**Comment by caltrider** [comment]
@alanmoo I hope so. I'm working with Janice and Bram on the Roku privacy policy stuff and hope she'll be able to finish this as part of that roll out.

**Comment by natalieworth** [comment]
@caltrider Could I close this? Think we just ran out of time so not sure if it's relevant anymore.

**Comment by caltrider** [comment]
@natalieworth Yes, you can close this.
