### ISSUE TITLE
Update navigation of *PNI

### ISSUE THREAD

**Issue by alanmoo** [mozilla/advocacy.mozilla.org#497]
Redpen: https://redpen.io/p/ajf2da463e476f3864

**Comment by natalieworth** [comment]
@gvn @alanmoo This slipped off my radar, but we'll have to update the image that gets shared on the PNI site. @beccaklam and I want to use this one: https://drive.google.com/drive/u/1/folders/13qllPp4vO6VikJEkC5dUS-wb_ltxhLw3

**Comment by gvn** [comment]
@natalieworth since that's unrelated to this ticket (this is just for the nav update) can you file a separate ticket to change the image?

**Comment by natalieworth** [comment]
yeah defs
