### ISSUE TITLE
Add favicon to site

### ISSUE THREAD

**Issue by kristinashu** [mozilla/advocacy.mozilla.org#50]
Please add the mozilla 'm' fav icon to http://advocacy.mozilla.org/ 
I think the previous version of the site had it.

**Comment by tripad** [comment]
Do we use the Mozilla icon or the Mozilla Advocacy icon ?

**Comment by kristinashu** [comment]
Just the Mozilla icon (like on https://teach.mozilla.org/) would be great.

**Comment by alicoding** [comment]
This is done
