### ISSUE TITLE
Fix bug where user can't close pop up because of sticky header

### ISSUE THREAD

**Issue by beccaklam** [mozilla/advocacy.mozilla.org#505]
- [ ] Found a bug on mobile where when the pop up comes because of the sticky header the user can't close the pop up and essentially is stuck on the page. This should probably get fixed:
<img width="375" alt="screen shot 2018-01-31 at 11 01 13 am" src="https://user-images.githubusercontent.com/20977376/35632950-1667fa26-0676-11e8-9512-d2d089e3d13a.png">

**Comment by alanmoo** [comment]
STR:

1. On `pni-refresh` branch, navigate to a product page on mobile (http://localhost:8000/privacynotincluded/category/toys/edwintheduck
2. Start scrolling.

(I think this is tied to sessionStorage, so you may have to open in a private tab)

**Comment by Pomax** [comment]
Ah, this only occurs when the browser window is smaller than the popup notice; I've adjusted the z-index for the modal so that it sits on top of all page content, even on small screens, which should resolve this.

**Comment by alanmoo** [comment]
Landed in master, thanks @Pomax
