### ISSUE TITLE
Scope adding Ford logo to OWF site

### ISSUE THREAD

**Issue by Melechuga** [mozilla/advocacy.mozilla.org#51]
We've forgotten to add Ford Foundation's logo to the OWF site. Questions I have:
1. What is the process for  adding an external org's logo? (i.e. is legal or code review necessary?) 
2. Assuming this isn't an issue, what would the timeline (from our side) be? Design, dev, updating, etc.
3. What do we need from Ford?

If I've missed any questions that should be considered, please include them in this issue. Thanks!
cc: @brettgaylor  @cassiemc @kristinashu @ScottDowne (Not sure if Kristina + Scott would still be on point for this.)

**Comment by kristinashu** [comment]
We would need a vector (.eps) version of the Ford Foundation logo and any copy they want to have with it (ex. "in partnership with"). Would the logo need to be on all three of the fellowship pages or just on the overview page?

I can do design for this next week if we have the logo.

**Comment by Melechuga** [comment]
Thanks @kristinashu. I think it only needs to be on the "overview" page above the footer. I've asked Ford for logo and text. Will update here asap.

**Comment by Melechuga** [comment]
Added Ford Foundation's logo (PDF + eps versions) to the logo folder. 
https://drive.google.com/open?id=0BybHRPPm37TJRzZNMklmYUFqUDQ
Will update here with the text as soon as we get it from them. @kristinashu

**Comment by Melechuga** [comment]
@kristinashu This is the text Ford has asked us to include:

The Ford Foundation works around the world on the frontlines of social change to fight inequality, strengthen democratic values, reduce poverty and injustice, and advance human achievement. Learn more at [FordFoundation.org](http://www.fordfoundation.org/)

Happy to discuss design ideas; at the moment, I think the best placement is below the "apply now" banner, but above the footer. Thoughts?

**Comment by kristinashu** [comment]
@Melechuga @cassiemc I've added the logo and description to the bottom of the overview page https://redpen.io/p/wt1d64bfb93fa6a6b8 - let me know what you think.

Is there a rush for this? Scott is away this week so he won't be able to do it but if it's important I'm sure we could find someone to make the update.

**Comment by Melechuga** [comment]
@kristinashu 
Thanks for doing this so quickly! It would be good to have this up asap, though it's not a blocker for anything else. I've added 2 comments regarding placement.

**Comment by kristinashu** [comment]
@Melechuga I've updated the link, let me know if it working better now: https://redpen.io/p/wt1d64bfb93fa6a6b8

**Comment by kristinashu** [comment]
Closing this ticket and opened an implementation one https://github.com/mozilla/advocacy.mozilla.org/issues/57

Scott is actually away for a couple weeks so seeing if someone else can do it.
