### ISSUE TITLE
Remove holiday references from buyer's guide

### ISSUE THREAD

**Issue by alanmoo** [mozilla/advocacy.mozilla.org#510]
In this folder: https://github.com/mozilla/advocacy.mozilla.org/tree/master/buyers-guide-locales/en-US
These files all have copy that needs to be updated, base on a search for "this holiday season" (probably with new keys for the purposes of translation, @TheoChevalier, please confirm). 

Home.properties
Products.properties
Share.properties
Why-we-made-this.properties

Edit from below: New copy at https://docs.google.com/document/d/1_ajXvK2HfB09pzSjHmDinCaEDNvtdqPGsccBMe2L2l0/edit

**Comment by TheoChevalier** [comment]
@alanmoo Yes, new keys please. It may not be possible to do for strings in products.properties though, as I think keys are read dynamically. So for this one I will manually remove the Spanish translation once the copy is updated.

(Passing by note, mentions in edits don’t trigger notifications 😉 )

**Comment by caltrider** [comment]
@alanmoo @TheoChevalier What's the best way to get you all the updated copy?  Could it be as simple as replace the word "gift" with the word "stuff" and remove all "this holiday season" strings?

Also, Alan, I think I submitted a ticket a couple weeks back to change the word "gift" to "stuff" on the landing page. Do you see that ticket?

**Comment by alanmoo** [comment]
@TheoChevalier I knew that was going to happen, but I also know you're pretty good at spotting new tickets :) (Also I got distracted 😁 )

@caltrider I didn't see that ticket, but it's the same files, so this can cover that work too. If changing words/removing holiday references is what you want, great, I can assign this ticket. Just confirm that is the solution we should go with.

**Comment by tlasadea** [comment]
Hey @caltrider @alanmoo @TheoChevalier I did this, it's [here](https://docs.google.com/document/d/1_ajXvK2HfB09pzSjHmDinCaEDNvtdqPGsccBMe2L2l0/edit). Hopefully this is what you were after  Alan!

**Comment by alanmoo** [comment]
Great, thanks!

**Comment by ScottDowne** [comment]
@TheoChevalier looks like there is only one string change proposal in products.properties so I think I can handle this somehow and still keep the old one.

**Comment by ScottDowne** [comment]
@TheoChevalier @alanmoo I think this should do the trick https://github.com/mozilla/advocacy.mozilla.org/pull/511

**Comment by caltrider** [comment]
Thank you @tlasadea ! And @TheoChevalier and @alanmoo and @ScottDowne .  Thanks everyone for doing this.
