### ISSUE TITLE
Remove cfp from open web fellowship pages

### ISSUE THREAD

**Issue by auremoser** [mozilla/advocacy.mozilla.org#514]
cc 
@alanmoo 

Reference issue #493

I'd like to remove or comment out the "apply to host" button on the [Overview page](https://advocacy.mozilla.org/en-US/open-web-fellows/overview), as applications closed on February 16th.

We'll be migrating to the foundation.mozilla.org for our next CFP (hopefully!), so I would like to remove these, but possibly keep the code idle in case we need to feature a future cfp here. It is present in the header and footer as pictured below, and I believe those are the only references.

### Header: 
*please remove the button but it's fine to keep the regular header title/images*
![screen shot 2018-02-22 at 9 08 43 pm](https://user-images.githubusercontent.com/1559703/36574691-ef8317c8-1814-11e8-806b-5d0e411f9f66.png)

### Footer: 
*please remove this footer entirely, not sure there was a non-cfp placeholder previously*
![screen shot 2018-02-22 at 9 08 37 pm](https://user-images.githubusercontent.com/1559703/36574694-f3f017de-1814-11e8-8b9e-9350e47b6793.png)

**Comment by ScottDowne** [comment]
There are apply buttons at the bottom of the year pages too:
https://advocacy.mozilla.org/en-US/open-web-fellows/fellows2017
https://advocacy.mozilla.org/en-US/open-web-fellows/fellows2016
https://advocacy.mozilla.org/en-US/open-web-fellows/fellows2015

All have them. We want those gone too yeah?

**Comment by gvn** [comment]
Removed 'em all!
