### ISSUE TITLE
Updates to OWF site: open applications for fellows -> redirect to foundation

### ISSUE THREAD

**Issue by auremoser** [mozilla/advocacy.mozilla.org#527]
cc 
@kristinashu 
@ScottDowne 
@community-impact
@annmarie123 

## Context
The fellowship applications open today, and it occurs to me that we should probably setup redirections on our previous sites (Advocacy and Science) so folks looking there can be pointed to the appropriate application site: https://foundation.mozilla.org/fellowships/apply

My suggestion is to just uncomment previous "applications open" features for Host Orgs, but instead for Fellows. Perhaps we can just enable the banners from our Host Org apps last month and make the button link redirect to https://foundation.mozilla.org/fellowships/apply?

**To do:**

* top banner: add Apply Now button on all fellowship pages - redirect to Foundation Site
* bottom banner: update copy and button link

## Details

**Header Button for Overview and Info page:**
Button: APPLY NOW! (link to https://foundation.mozilla.org/fellowships/apply/)
Comp: https://redpen.io/bm7d04073bd8dcd2d6

**Bottom banner copy for Fellows page:**
Copy: 
We are an inclusive program and seek Fellows that reflect the diversity of the communities we serve. We encourage unique contributors with varied backgrounds to apply; if you feel your perspective is under-represented in technology, we want to hear from you!
Button: APPLY TO BECOME A FELLOW! (https://foundation.mozilla.org/fellowships/apply/)
*Deadline 5:00PM ET April 20, 2018*

Comp: https://redpen.io/bm7d04073bd8dcd2d6

Here are all of the comps that Kristina shared with me: https://redpen.io/p/wt1d64bfb93fa6a6b8. 
![screen shot 2018-03-21 at 1 42 54 pm](https://user-images.githubusercontent.com/1559703/37710403-d5d8b07c-2d0d-11e8-9cd0-6066b0b32d98.png)
Let me know if this isn't enough info! Thank you!

**Comment by alanmoo** [comment]
Is there any reason we shouldn’t just forward all traffic from those pages automatically to the new fellowships site?

**Comment by auremoser** [comment]
We have a lot more on those sites than just the apply now buttons, for example, net policy blog and some of our campaigns are featured there. I think it would probs be a longer discussion about the utility of that whole collection of pages than might be reasonable rn. 

Happy to discuss but since the page is live, the site probably won't be shut down in a while, and we ran the host org applications there folks might be looking at that site to learn more. Plus, we have no page that highlights specifically our partnership with Ford for the OWF program, so if we ever want to do specific campaigning around that, it's nice to point to a more specific site. 

I'm o.k. with this being rejected, but I'm updating the science site with the same redirection process.

**Comment by alanmoo** [comment]
That's fine, just wanted to put it out there as an option.
