### ISSUE TITLE
[Plan] Open Web Fellows 2016 Communications Plan

### ISSUE THREAD

**Issue by Melechuga** [mozilla/advocacy.mozilla.org#53]
*Detailed goals in Open Web Fellows 2016 Comms Plan [Google Docs] (https://docs.google.com/document/d/1x8lUU_rUF-WfgQNjyaI-u6fQ8IG1hLrjeJai3TrZ7U0/edit)*

**RASCI:**
R: Kevin Zawacki @KevZawacki 
A: Paul Johnson @HPaulJohnson 
S: Brett Gaylor @brettgaylor  Melissa Romaine
C: Fellows, Sam Burton, host org. communications teams
I: MoFo comms

**Overview:**
The first quarter of 2016 marks a major moment for Mozilla’s Advocacy network: the first-ever cohort of Ford-Mozilla Open Web Fellows will graduate from their placement organizations. As this occurs, Mozilla will reflect on fellows’ work and impact, and fellows will embark on the next step of their careers as OWF alums. 

Starting in February, Mozilla will also open the application process for its second cohort of Open Web Fellows. This class will be more policy-focused than the last, and boast heightened reach — fellows will embed at organizations in Nairobi, Santiago, Brussels and elsewhere around the world.

The [Communications Plan] (https://docs.google.com/document/d/1x8lUU_rUF-WfgQNjyaI-u6fQ8IG1hLrjeJai3TrZ7U0/edit) (linked above) outlines strategies and tactics for communicating these developments with the world.

**Links:**
[OWF blog] (https://docs.google.com/document/d/1ArP7FlUMLPepoLExDCq7EzfdK_wjH6NsqmXRgNPhCLA/edit)
[OWF narrative] (https://docs.google.com/document/d/1WRLUoMaoWvG1z_ASsQ0_WJ7NYj8E2W0Aqc6dHpZlM1U/edit)
[OWF call notes] (https://docs.google.com/document/d/12xez8TBjn86wPFWdnxBiAlXgYqy6RPN8cj0QN79PnsQ/edit#)

**KPIs:**
- [ ] 1 capstone blog spotlighting OWF program and enticing 2016 applicants
- [ ] 1 email engaging unselected host orgs 2016 applications
- [ ] 1-2 positive, factual stories in tech/policy/privacy press spotlighting OWF program
- [ ] Strong showing on all owned channels: email, project call, social

**Calendar and Tactics:**
- [x] **Jan. 22:** Kevin and Melissa determine blog structure and content
- [x] **Jan 25:** Kevin beings interviews with OWFs and host orgs. See progress [here] (https://docs.google.com/document/d/1ArP7FlUMLPepoLExDCq7EzfdK_wjH6NsqmXRgNPhCLA/edit)
- [x] **Feb. 1:**  Application open for 2016 fellows
- [x] **Feb 1:** Melissa on all hands call
- [x] **Feb. 2:** Begin promoting application portal on social
- [ ] **Feb 11:** Email to unselected host orgs (Melissa) 
- [ ] **Feb 17:** Publish blog post on blog.mozilla.org/netpolicy
- [ ] **Feb 17:** Pitch media
- [ ] **Feb. 18:** Promote blog on social 
* *Mar 1 - May 31: Current fellows being to graduate*
- [ ] **Mar. 20:** Applications close
* *Mar. 30 - Apr 1: RightsCon*
- [ ] **Mar 29:** Emerging leaders event
* *May/June (Sept?)*
- [ ] 2016 fellows announced
- [ ] Published announcement on blog.mozilla.org
- [ ] Re-pitch media

**Comment by Melechuga** [comment]
FYI Had to stick this in this repo bc I don't have access to the mofo/plan repo.

**Comment by cassiemc** [comment]
You should have access now if you'd like to move it.

**Comment by Melechuga** [comment]
Moved to MoFo/plan repo: https://github.com/MozillaFoundation/plan/issues/720
