### ISSUE TITLE
Update Codemoji feedback email link

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/advocacy.mozilla.org#538]
Hey @alanmoo 
I need the Feedback link on the [Codemoji page footer](https://codemoji.org/#/welcome) updated from askjoin@mozilla.org to network@mozillafoundation.org. We'll be retiring askjoin@ in the next couple of weeks.

**Comment by alanmoo** [comment]
Updated in https://github.com/mozilla/codemoji/commit/d3ce3bf342c38935d5901f11df78bd66495f8f02
