### ISSUE TITLE
Correct typo on advocacy.mozilla.org

### ISSUE THREAD

**Issue by KevZawacki** [mozilla/advocacy.mozilla.org#56]
Hi there, 

Small change needed to advocacy.mozilla.org subhead. "Mozilla" at the start of the third paragraph should be capitalized:

![advocacy typo](https://cloud.githubusercontent.com/assets/11045250/12932417/8c9b85c8-cf37-11e5-9bf0-631551040f83.png)
 
@kristinashu, are you able to make this change?

**Comment by kristinashu** [comment]
Sorry @KevZawacki I'm not able to make this update. It would be Scott but he's on PTO. @alicoding any chance you would be able to do this?

**Comment by alicoding** [comment]
I just fixed it in my local development branch. This will be done part of the encryption campaign, so when we land the page it should have the fix. Unless this is urgent I can make another pull request now.

**Comment by KevZawacki** [comment]
Works for me -- thanks all!

**Comment by kristinashu** [comment]
That was so fast! Thanks!

**Comment by kristinashu** [comment]
Update is live https://advocacy.mozilla.org/
