### ISSUE TITLE
Implement add Ford logo to OWF site

### ISSUE THREAD

**Issue by kristinashu** [mozilla/advocacy.mozilla.org#57]
We need to add a section to https://advocacy.mozilla.org/open-web-fellows/

Needs to include: Ford Foundation logo, description and link to their site https://www.fordfoundation.org/

Based on design in https://github.com/mozilla/advocacy.mozilla.org/issues/51
here is the comp https://redpen.io/p/wt1d64bfb93fa6a6b8

Assets:

Ford logo svg: https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLMWNhQ1dFbFFXVmM/view?usp=sharing

Copy: SUPPORTED BY
The Ford Foundation works around the world on the frontlines of social change to fight inequality, strengthen democratic values, reduce poverty and injustice, and advance human achievement. Learn more at FordFoundation.org

Body text is same as the rest of the body text. "Supported by" is: 14px, italic, #7f7f7f

Light grey background colour: #efefef

@alicoding would you please be able to do this?

**Comment by ScottDowne** [comment]
@alicoding review? https://github.com/mozilla/advocacy.mozilla.org/pull/68

**Comment by ScottDowne** [comment]
It's live

**Comment by kristinashu** [comment]
Excellent, thanks! 

cc @Melechuga

**Comment by Melechuga** [comment]
Thank you!
