### ISSUE TITLE
"Join the conversation" element is out of line on encrypt page

### ISSUE THREAD

**Issue by drewrwilson** [mozilla/advocacy.mozilla.org#90]
The new site is beautiful! I noticed what may be a bug. The "Join the Conversation" link on the [encrypt main page](https://advocacy.mozilla.org/encrypt/) is not in line with the other links on that site. Not sure if intentional or a bug.

![image](https://cloud.githubusercontent.com/assets/4324656/13119199/ed38ef3a-d575-11e5-895f-99f32bae3cf2.png)

Chrome Version 48.0.2564.109 (64-bit) on MacOS

**Comment by brettgaylor** [comment]
Fixed!  Thanks, Drew!

**Comment by alanmoo** [comment]
Yup, this was a bug in Chrome for some odd reason. Should be fixed now, thanks for reporting it!
